server:
  tomcat:
    max-connections: 10000
    threads:
      max: 300
      min-spare: 300
    max-keep-alive-requests: 1000
    keep-alive-timeout: 30000

spring:
  datasource:
    url: jdbc:mysql://172.31.9.189:3306/reservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: app_user
    password: apppassword123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: 172.31.1.90
      port: 6379

payment:
  secret-key: "production-super-secret-key-for-hmac-that-is-very-long-and-random-2024"
  payments-server-url: "http://172.31.0.179:8080"

logging:
  level:
    root: ERROR
