server:
  tomcat:
    max-connections: 10000
    threads:
      max: 300
      min-spare: 300
    max-keep-alive-requests: 1000
    keep-alive-timeout: 30000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

payment:
  secret-key: "???"
  payments-server-url: "http://localhost:9090"

logging:
  level:
    root: ERROR
